name: release

on: 
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: mv dist public
      - run: tar -czvf public.tar.gz public
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: public.tar.gz application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}